apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: login-deployment
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nginx
    spec:
      volumes:
       - name: task-pv-storage
         persistentVolumeClaim:
           claimName: login-pv-claim
      containers:
       - name: nginx-container
        # Run this image
        image: jayanthpodila/ecomm:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage

